export const images = {
  splash: require('../assets/images/Splashimg.png'),
  whtsplogo: require('../assets/images/whtsplogo.png'),
  phone: require('../assets/images/phone.png'),
  uncheck: require('../assets/images/unchecked.png'),
  check: require('../assets/images/check.png'),
  back: require('../assets/images/back.png'),
  logo: require('../assets/images/Whatsapp.png'),
  logout: require('../assets/images/power.png'),
  update: require('../assets/images/updated.png'),
  account: require('../assets/images/account.png'),
  search: require('../assets/images/magnifying_glass.png'),
  threeDot: require('../assets/images/menu.png'),
  videoCamera: require('../assets/images/video_camera.png'),
  telephone: require('../assets/images/telephone.png'),
};
